ProjetoEstoqueDDD.MVC/ViewModels/EstoqueViewModel.cs
using System;

namespace ProjetoEstoqueDDD.MVC.ViewModels
{
    public class EstoqueViewModel
    {
        public int EstoqueId { get; set; }
        public int Quantidade { get; set; }
        public string Type { get; set; }
        public DateTime Date_Criado { get; set; }
        public int ProdutoId { get; set; }

        public virtual ProdutoViewModel Produto { get; set; }
    }
}

ProjetoEstoqueDDD.MVC/ViewModels/ProdutoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ProjetoEstoqueDDD.MVC.ViewModels
{
    public class ProdutoViewModel
    {
        [Key]
        public int ProdutoId { get; set; }
        [Required(ErrorMessage = "Preencha o campo nome")]
        [MaxLength(150, ErrorMessage = "Máximo {0} caracteres")]
        [MinLength(2, ErrorMessage = "Minimo {0} caracteres")]
        public string Nome { get; set; }
        [DataType(DataType.Currency)]
        [Required(ErrorMessage = "Preencha o campo valor")]
        [Range(typeof(decimal),"0","999999999999")]
        public double Valor { get; set; }
        [ScaffoldColumn(false)]
        public DateTime Date_Criado { get; set; }
        [ScaffoldColumn(false)]
        public DateTime Date_Alterado { get; set; }
        public bool Ativo { get; set; }
        public int Quantidade { get; set; }

        public IEnumerable<EstoqueViewModel> Estoque { get; set; }
    }
}

ProjetoEstoqueDDD.MVC/Controllers/EstoqueController.cs
using AutoMapper;
using ProjetoEstoqueDDD.Domain.Entidades;
using ProjetoEstoqueDDD.Infra.Data.Repositorios;
using ProjetoEstoqueDDD.MVC.ViewModels;
using System.Web.Mvc;

namespace ProjetoEstoqueDDD.MVC.Controllers
{
    public class EstoqueController : Controller
    {
        private readonly EstoqueRepositorio _estoqueRepositorio = new EstoqueRepositorio();

        // GET: Produto/Details/5
        public string ModificarEstoque(string type, int produtoid)
        {
            EstoqueViewModel estoqueGravar = new EstoqueViewModel();
            estoqueGravar.ProdutoId = produtoid;
            estoqueGravar.Quantidade = 1;
            estoqueGravar.Type = type;
            var estoqueDomain = Mapper.Map<EstoqueViewModel, Estoque>(estoqueGravar);
            _estoqueRepositorio.Add(estoqueDomain);

            //Poderia usa metodo do repositorio no Infra.data do estoque para pega as informações de estoque.

            return "Atualizado com Sucesso"; //poderia retorna em formato json.
        }
    }
}

ProjetoEstoqueDDD.MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjetoEstoqueDDD.MVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ProjetoEstoqueDDD.MVC/Controllers/ProdutoController.cs
using AutoMapper;
using ProjetoEstoqueDDD.Domain.Entidades;
using ProjetoEstoqueDDD.Infra.Data.Repositorios;
using ProjetoEstoqueDDD.MVC.ViewModels;
using System.Collections.Generic;
using System.Web.Mvc;

namespace ProjetoEstoqueDDD.MVC.Controllers
{
    public class ProdutoController : Controller
    {
        private readonly ProdutoRepositorio _produtoRepositorio = new ProdutoRepositorio();
        private readonly EstoqueRepositorio _estoqueRepositorio = new EstoqueRepositorio();
        // GET: Produto
        public ActionResult Index()
        {
            var produtoViewModel = Mapper.Map<IEnumerable<Produto>, IEnumerable<ProdutoViewModel>>(_produtoRepositorio.GetAll());
            foreach (var datapro in produtoViewModel)
            {
                datapro.Quantidade = _estoqueRepositorio.QuantidadeEstoque(datapro.ProdutoId);
            }

            return View(produtoViewModel);
        }

        // GET: Produto/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Produto/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Produto/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Produto/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Produto/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Produto/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ProjetoEstoqueDDD.MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ProjetoEstoqueDDD.MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ProjetoEstoqueDDD.MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

ProjetoEstoqueDDD.MVC/Views/Produto/Index.cshtml
@model IEnumerable<ProjetoEstoqueDDD.MVC.ViewModels.ProdutoViewModel>

@{
    ViewBag.Title = "Controle de Estoque Para José";
}
<div class="alert alert-success hide" role="alert"></div>
<div class="alert alert-danger hide" role="alert"></div>
<div class="row m-t-30">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">Controle de Produtos</div>
            <div class="panel-body table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <th>Produto(s)</th>
                        <th>Quantidade</th>
                    </thead>
                    <tbody class="columns">
                        @foreach (var item in Model) {
                            <tr class="rowlinha">
                                <td>@item.Nome</td>
                                <td>
                                    <form class="form-inline">
                                        <div class="form-group">
                                            <div class="input-group">
                                                <a href="#" class="input-group-addon btn atualizarestoque">-</a>
                                                <input type="text" class="form-control atuprod" id="quantidade" value="@item.Quantidade" placeholder="Quantidade">
                                                <input name="produtoid" class="produto" type="hidden" value="@item.ProdutoId">
                                                <a href="#" class="btn input-group-addon atualizarestoque">+</a>
                                            </div>
                                        </div>
                                    </form>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

ProjetoEstoqueDDD.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Controle De Estoque", "Index", "Produto", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início", "Index", "Produto")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Willian ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>